- index.html
Minor tweaks to show the Chrome version in `index.html`, `io.js` -> `node`, and also a few formatting tweaks.
> Add Chrome version and mention node

- LICENSE.md
- README.md
- package.json
We can more easily build our own app based on this code if it is public domain.
Allowance by @johnmuhl, @IonicaBizau and @Shriken might be required too...?
> Change license to CC0

- index.html
- main.js
http://electron.atom.io/docs/v0.35.0/tutorial/quick-start/
> Made Changes Based on Electron Quick Start Guide

- main.js
See https://github.com/atom/electron/pull/3826 for more details
Refs https://github.com/atom/electron/issues/3673
> Remove call to crashReporter.start()

- README.md
Let's make this copy/paste able.
> Remove $ in code example

- index.html
> -> Chromium

- README.md
- package.json
`github.com/atom` -> `github.com/electron`
> Update urls for new GitHub org

- README.md
- index.html
- main.js
- package.json
- renderer.js
This PR makes some updates to the project, mostly comments, geared towards making the parts of this Electron app more defined (i.e. renderer and main processes).
It also updates to use a newer version of Electron.
cc @kevinsawicki @zeke
> Make updates

- main.js
This pull request updates the main.js file to use [standard javascript style](http://standardjs.com/).
@jlord
> use standard style

- main.js
This is not very important, but as there are `const` and `let`, I thought about using string interpolation too
> Use string es6 interpolation

- README.md
A companion to https://github.com/electron/electron/pull/6495
> link to boilerplates

- package.json
We can [npm install electron](http://electron.atom.io/blog/2016/08/16/npm-install-electron) directly!  :tada:
> 🎉 npm install electron --save-dev

- README.md
> Update license text in README

- index.html
Node should be capitalized.
Yes, this is nitpicky.
> fix Node capitalization

- README.md
Fixed Readme Quick Start Guide links that 404.
> Fix Readme Quick Start Guide links

- package.json
Drinking our own Kool-Aid™, or whatever the expression is.
See https://github.com/electron/electron/pull/8897
cc @malept
> use safer semver range for electron

- README.md
This PR adds some useful links to the README
> update readme with links to more guides and examples

- main.js
I feel like people should know how to do this but I have personally seen people getting confused as to why the developer tools show up. This would make it so you are not required to even touch this file when setting up a quick application.
> Comment out enabling dev tools

- README.md
Added a warning for Windows 10 users facing npm errors. Most of the times that's the problem
> Warning for Win10 on readme

- package.json
electron version updated to latest
> electron upgrade to 1.8.4

- main.js
In coordination with https://github.com/electron/electron/pull/13013 , update the index loading functionality to leverage the new `loadFile()` method in the `BrowserWindow` module.
/cc @zeke
> feat: update index loading for new API

- package-lock.json
- package.json
Update Electron to [v3.0.0](https://github.com/electron/electron/releases/tag/v3.0.0).
> chore: Update Electron to v3.0.0.

- package-lock.json
- package.json
Update Electron to [v3.0.3](https://github.com/electron/electron/releases/tag/v3.0.3).
> chore: Update Electron to v3.0.3.

- package-lock.json
- package.json
Release information:
https://github.com/electron/electron/releases/tag/v3.0.4
> chore(electron): update electron to version 3.0.4 to include latest bugfixes

- package.json
updated electron version in devDependencies from 3.0.7 to 4.0.1
> chore: updated electron version to 4.0.1

- main.js
Fixes an issue on Electron 5 where the versions weren't printed to the renderer 👍
> fix: specify nodeIntegration=true for Electron 5 compat

- index.html
- main.js
- preload.js
Per https://github.com/electron/electron/pull/18045#pullrequestreview-231912547
If this is approved, I'll file a PR for the Electron docs as well.
> feat: use a preload script instead of enabling nodeIntegration

- preload.js
This PR just removes trailing spaces.
This project does not have any lint settings, but most lint styles disallow trailing whitespaces.
> chore: Remove trailing space

- main.js
Ref https://github.com/electron/electron/21957
> chore: no need to hold on to mainWindow reference

- main.js
fixes https://github.com/electron/electron/issues/23476
> fix: don't listen to 'activate' until ready

- index.html
- main.js
- preload.js
As the commit says, this is a first draft of what a test template would look like in electron-quick-start. Goals of this PR:
1. Get consensus via PR review about what such a template should look like, e.g. having _just enough_ useful helper code. This is something we've discussed but now it's time to merge something :smiley: 
2. Discuss where such a template should live. This PR targets the `test-template` branch because, if we keep that branch permanently, then it's a short hop for [Fiddle](https://github.com/electron/fiddle) to pull the template from `https://github.com/electron/electron-quick-start/archive/test-template.zip` when the 'New Test' button is clicked.
CC @erickzhao, @clavin, @groundwater. Also pinging @malept and @nornagon who have shown related interest
> feat: first draft of a test template

- main.js
fix oops in the test template, reported by @nornagon
> fix: test template undefined

- main.js
Signed-off-by: Darshan Sen <darshan.sen@postman.com>
> chore: remove trailing space in main.js

- README.md
- preload.js
- renderer.js
> docs: update comments to reflect new defaults

- .github/CODEOWNERS
- README.md
- index.html
- main.js
- package-lock.json
- package.json
- preload.js
- renderer.js
- styles.css
* Merges in `main` and fixes conflicts
* Fixes `standard` linting errors for the JS
Not sure this is the cleanest way to do this, so suggestions welcome.
> chore: update test-template

- main.js
Refs https://github.com/electron/electron/pull/39681. Let's bring it here as well since this repo is effectively documentation.
> chore: use node prefix with path module

- package-lock.json
- package.json
This PR updates the repo name in `package.json` and `package-lock.json`
> chore: updates package.json and package-lock.json
