electron/minimal-repro

README.md
My English teacher(s) told us that if `/^(a|e|i|o|u)/i.test(nextWord) === true`, we should use *an* instead of *a*. :joy: 
So, I guess here we need just *a basic* instead of *an basic*. :smile:
=> Fix typo in description

main.js
[Electron v0.33.4] moved `openDevTools` from `BrowserWindow` to `WebContents`
[Electron v0.33.4]: https://github.com/atom/electron/releases/tag/v0.33.4
=> Replace deprecated use of `bw.openDevTools`

package.json
Because it uses an old Electron version!
=> upgrade electron

main.js
This adds adds an activate event so that the window is recreated, after all have been closed, and the dock icon is clicked. This is common behavior on OS X and otherwise you're left with the menu and icon of an app but now way to restore it. 
It also cleans up some code comments and uses a stricter platform check.
cc @kevinsawicki
=> Restore window on activate event

package.json
I just discovered that `electron-prebuilt` is kept up to date automatically!
From http://maxogden.com/electron-fundamentals.html
> I'd also like to give a shoutout to John Muhl who wrote [electron-prebuilt-updater](https://github.com/johnmuhl/electron-prebuilt-updater), which runs on a free Heroku server, listens for GitHub Releases on Electron with a WebHook and automatically does an NPM publish to `electron-prebuilt` with the new release. It's an awesome bit of automation that has saved me a lot of maintenance time!
@jlord
=> bump electron prebuilt to ^0.37.8

package.json
npm falls back to `repository` if `homepage` is absent, so this value was redundant. Also the npm website infers the issues URL automatically for GitHub-based packages.
=> Use new electron version and clean up package.json

README.md, main.js
Currently, if your app's folder contains certain special URL characters (such as `?`) then the quick start app does not work because those values aren't properly encoded before passing the URL to `BrowserWindow.loadURL`.
- Clone this repository into a folder called `quick?start`
- Run `npm start`
- Fails with an error like `Not allowed to load local resource: file:///Users/kevin/github/electron-scratch/quick?start/index.html`
/cc @zeke
=> Format URL passed to BrowserWindow.loadURL

README.md
The wording is awkward. I think removing "an" works. Alternatively, adding the word "application" after "Electron" works too.
=> Remove "an" from intro

README.md
http://electron.atom.io/docs/tutorial/quick-start/ -> Replaces links that were 404ing
http://electron.atom.io/docs/ -> Replaces a link that was redirecting via 301
=> Fix links that 404 or redirect

index.html
`<script>` was placed in `<html>`, which is not valid HTML (according to [W3C validator](http://validator.w3.org/)). It is now placed at the end of `<body>`.
=> Place <script> in <body>

package.json
now that we have a stable 1.8.x version in npm, bump our dependency from 1.7.x to 1.8.x
=> bump electron devDependencies to 1.8.2

README.md
`electronjs.org` instead of `electron.atom.io`
=> Use the new domain of the Electron project in the README file

package-lock.json
This PR fixes the single moderate vulnerability exposed via `npm audit`.
Also commits the `package-lock` file.
/cc @zeke
=> Fix single moderate dependency vulnerability

main.js
OS X is no longer the name of Apple's Mac operating system, it was changed to macOS at WWDC 2016
=> chore: update comments to refer to 'macOS' instead of 'OS X'

package-lock.json
I updated the package-lock.json which was generated with electron 4.0.1. By the time i add this commit the previous PR got merged. LOL !
=> chore: package-lock.json updated for electron 4.0.1

main.js
In this PR, I simplified the IF statements by removing the curcly braces and removing the indent. 
In other words, I turned this:
```js
if (process.platform !== 'darwin') {
app.quit()
}
```
into this:
```js
if (process.platform !== 'darwin') app.quit()
```
=> style: Simplify if statements

preload.js
Closes https://github.com/electron/electron-quick-start/issues/295.
This preload script previously assumed these elements to be present in the DOM, which is not the case if any other page is loaded. This corrects that issue by only attempting to replace the `innerText` if the element is non-null.
cc @malept
=> fix: faulty preload selector assumptions

renderer.js
It seems like this comment was left in `renderer.js` from an earlier version. Corrected it to the best of my ability. Let me know if I've misunderstood something.
=> chore: renderer has no access to Node APIs.

index.html
Closes https://github.com/electron/electron-quick-start/issues/333.
Adds a CSP so that the default does not throw console warnings. Also includes a link to CSP documentation.
cc @jkleinsc
=> security: add csp

main.js
Similar to https://github.com/electron/electron/pull/21972: prefer `app.whenReady(...)` over `app.one('ready', ...)` for the minor advantage of not leaving a live-but-never-agan-used event handler laying around.
CC @codebytere
=> refactor: use app.whenReady(), not of .once(ready)

main.js
I fixed the comment above the auto-quit prevention for macOS.
Before it suggested the code quits the app, now it says the code prevents the app from quitting.
**Note**: This same pull request was on [Electron \#24003](https://github.com/electron/electron/pull/24003). I added it here too for consistency.
=> docs: fix explanation of darwin auto-quit prevention

index.html
Per https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP :
> (Sometimes you may see mentions of the `X-Content-Security-Policy` header, but that's an older version and you don't need to specify it anymore.)
=> fix: remove X-Content-Security-Policy header

main.js
if the current test template is run on older versions of Electron, it will error out with
> "Error: companyName is a required option to crashReporter.start"
The template works in Electron 10 due to @nornagon's [update](https://github.com/electron/electron/commit/06bf0d08dc3c941ccce0dfb0f9e0e146d9232605) which is [described](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#deprecated-companyname-argument-to-crashreporterstart) in the breaking changes doc:
> The companyName argument to crashReporter.start(), which was previously required, is now optional, and further, is deprecated. To get the same behavior in a non-deprecated way, you can pass a companyName value in globalExtra.
Since the test template will ideally work on whatever version of Electron we throw at it, …
=> fix: do not start crashReporter on < Electron 10

preload.js
Fixes a use case like this:
```js
test.assert(foo());
test.done();
```
Let's say `foo()` returns false which triggers an ipcRenderer.send('test-done') event. The issue here is that, since control flow continues in the renderer even after the test failure, you can wind up having two ipc `test-done` calls -- one indicating failure (from `foo()`'s failure), and one indicating success (from `test.done()`.
The first message is usually processed quickly enough that the test application exits before the false-success from `test.done()` is handled by the main process. But there is no guaranteed. For whatever reason, 11.4.x nearly always gets the second `test-done` event before exiting, causing those versions to often show false successes.
Another fix would be to use `sendSync()` instead of …
=> fix: exit after all tests done or after test fail

index.html
This change will allow fiddle users and people using the quickstart to add inline `style` elements and `style` attributes, making it easier to quickly style without significantly damaging CORS.
We could also consider `script-src-attr` to only allow `style` attributes but I think allowing inline style elements would be useful as well.
=> CORS: Allow inline CSS and style attributes

main.js, preload.js
These files had become inconsistent with the code examples in the documentation on the website since those are linted with `standard`.
=> chore: lint JS with standard

preload.js
Simple text change to the comment at the top of the the default preload.js file. Clarifies what the preload script runs before.
=> fix: clarifies what preload script runs before

README.md
This PR updates the repo's README to reflect:
1. the new repo name `minimal-repro`
2. the adjusted purpose of the repo as a way to share minimal repros of Electron behavior rather than as an application starting point.
Merge once the repo has been renamed!
=> chore: Update README.md to reflect rename
